---
title: "first_pass_elvin"
author: "Elvin Liu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup}
library(dplyr)
library(purrr)
library(tidyr)
library(labelled)
```

```{r}
# map labels from txt to csv
lines <- readLines("J362221_labels.txt")
var_lines <- lines[grepl("^ER[0-9A-Z]+\\s+", lines)]

label_df <- data.frame(
  var   = trimws(sub("^(ER[0-9A-Z]+)\\s+.*$", "\\1", var_lines)),
  label = trimws(sub("^ER[0-9A-Z]+\\s+(.*?)\\s{2,}\\d{0,2}\\s*$", "\\1", var_lines)),
  stringsAsFactors = FALSE
)

df <- read.csv("J362221.csv", stringsAsFactors = FALSE)

for (i in seq_len(nrow(label_df))) {
  v <- label_df$var[i]
  if (v %in% names(df)) {
    var_label(df[[v]]) <- label_df$label[i]
  }
}
```

```{r}
# get rid of dupe family heads
df_no_dupes <- df %>%
  group_by(ER10002) %>%
  slice(1) %>%
  ungroup()
```

```{r}
# mapping from wide to long
wave_map <- list(
  "1997" = list(
    # Tracking IDs
    family_id      = "ER10002",
    person_id      = "ER33401", # Added from your "ID Number" line
    
    # Demographics & Geography
    state          = "ER12221",
    age            = "ER10009",
    sex            = "ER10010",
    n_children     = "ER10012",
    age_yng_child  = "ER10013",
    race           = "ER11848",
    education      = "ER12222",
    couple_status  = "ER12223C",
    relation       = "ER33403",
    emp_status     = "ER33411",
    rural_urban    = "ER12221A",
    
    # Housing
    type_du        = "ER10017",
    own_rent       = "ER10035",
    neither_own_rent = "ER10068", # Clarified label
    food_stamps    = "ER11065",
    
    # Health
    health_head    = "ER11723",
    health_wife    = "ER11727",
    parents_poor   = "ER11846",
    
    # Income/Needs
    total_income   = "ER12079",
    needs_standard = "ER12220",
    
    # Transfer Income
    wtr_adc        = "ER11272",
    amt_adc        = "ER11273",
    wtr_ssi        = "ER11287",
    amt_ssi        = "ER11289",
    wtr_welfare    = "ER11303",
    amt_welfare    = "ER11304",
    wtr_va         = "ER11319",
    amt_va         = "ER11322",
    wtr_nonva_ret  = "ER11336",
    amt_nonva_ret  = "ER11337",
    wtr_annuities  = "ER11351",
    amt_annuities  = "ER11352",
    wtr_otr_pen    = "ER11366",
    amt_otr_pen    = "ER11367",
    wtr_unemp      = "ER11382",
    amt_unemp      = "ER11383",
    wtr_workers_comp = "ER11397",
    amt_workers_comp = "ER11398",
    wtr_child_supp = "ER11412",
    amt_child_supp = "ER11413"
  ),
  "1999" = list(
    family_id      = "ER13002",
    person_id      = "ER33501",
    state          = "ER13004",
    age            = "ER13010",
    sex            = "ER13011",
    n_children     = "ER13013",
    age_yng_child  = "ER13014",
    type_du        = "ER13022",
    own_rent       = "ER13040",
    neither_own_rent = "ER13073",
    food_stamps    = "ER14284",
    wtr_adc        = "ER14538",
    amt_adc        = "ER14539",
    wtr_ssi        = "ER14553",
    amt_ssi        = "ER14555",
    wtr_welfare    = "ER14569",
    amt_welfare    = "ER14570",
    wtr_va         = "ER14585",
    amt_va         = "ER14588",
    wtr_nonva_ret  = "ER14602",
    amt_nonva_ret  = "ER14603",
    wtr_annuities  = "ER14617",
    amt_annuities  = "ER14618",
    wtr_otr_pen    = "ER14632",
    amt_otr_pen    = "ER14633",
    wtr_unemp      = "ER14648",
    amt_unemp      = "ER14649",
    wtr_workers_comp = "ER14663",
    amt_workers_comp = "ER14664",
    wtr_child_supp = "ER14678",
    amt_child_supp = "ER14679",
    health_head    = "ER15447",
    health_wife    = "ER15555",
    parents_poor   = "ER15926",
    race           = "ER15928",
    couple_status  = "ER16425",
    needs_standard = "ER16427",
    rural_urban    = "ER16431",
    total_income   = "ER16462",
    education      = "ER16516",
    relation       = "ER33503",
    emp_status     = "ER33512"
  ),
  # Repeat structural pattern for 2001-2007 blocks... - Elvin
  "2001" = list(
    family_id      = "ER17002",
    person_id      = "ER33601", # note: YYYY interview number
    state          = "ER17004",
    age            = "ER17013",
    sex            = "ER17014",
    n_children     = "ER17016",
    age_yng_child  = "ER17017",
    type_du        = "ER17025",
    own_rent       = "ER17043",
    neither_own_rent = "ER17084",
    food_stamps    = "ER18416",
    wtr_adc        = "ER18697",
    amt_adc        = "ER18698",
    wtr_ssi        = "ER18715",
    amt_ssi        = "ER18715",
    wtr_welfare    = "ER18730",
    amt_welfare    = "ER18731", # note: Other Welfare of Head ?= amount of welfare
    wtr_va         = "ER18747",
    amt_va         = "ER18750",
    wtr_nonva_ret  = "ER18765",
    amt_nonva_ret  = "ER18766",
    wtr_annuities  = "ER18781",
    amt_annuities  = "ER18782",
    wtr_otr_pen    = "ER18797",
    amt_otr_pen    = "ER18798", # note: Other OTR Pension ?= amount of otr pension
    wtr_unemp      = "ER18814",
    amt_unemp      = "ER18815",
    wtr_workers_comp = "ER18830",
    amt_workers_comp = "ER18831",
    wtr_child_supp = "ER18846",
    amt_child_supp = "ER18847",
    health_head    = "ER19612",
    health_wife    = "ER19720",
    parents_poor   = "ER19987",
    race           = "ER19989",
    couple_status  = "ER20371",
    needs_standard = "ER20373",
    rural_urban    = "ER20377",
    total_income   = "ER20456", # note: Total Family Income-2000
    education      = "ER20457",
    relation       = "ER33603",
    emp_status     = "ER33612"
  ),
  "2003" = list(
    family_id      = "ER21002",
    person_id      = "ER33701", 
    state          = "ER21003",
    age            = "ER21017",
    sex            = "ER21018",
    n_children     = "ER21020",
    age_yng_child  = "ER21021",
    type_du        = "ER21024",
    own_rent       = "ER21042",
    neither_own_rent = "ER21082",
    food_stamps    = "ER21681",
    wtr_adc        = "ER22069",
    amt_adc        = "ER22070",
    wtr_ssi        = "ER22085",
    amt_ssi        = "ER22087",
    wtr_welfare    = "ER22102",
    amt_welfare    = "ER22103",
    wtr_va         = "ER22119",
    amt_va         = "ER22120",
    wtr_nonva_ret  = "ER22135",
    amt_nonva_ret  = "ER2213",
    wtr_annuities  = "ER22151",
    amt_annuities  = "ER22152",
    wtr_otr_pen    = "ER22167",
    amt_otr_pen    = "ER22168",
    wtr_unemp      = "ER22184",
    amt_unemp      = "ER22185",
    wtr_workers_comp = "ER22200",
    amt_workers_comp = "ER22201",
    wtr_child_supp = "ER22216",
    amt_child_supp = "ER22217",
    health_head    = "ER23009",
    health_wife    = "ER23136",
    parents_poor   = "ER23424",
    race           = "ER23426",
    couple_status  = "ER24152",
    needs_standard = "ER24140",
    rural_urban    = "ER24144",
    total_income   = "ER24099", # note: Total Income of Last Year
    education      = "ER24148",
    relation       = "ER33703",
    emp_status     = "ER33712"
  ),

  "2005" = list(
    family_id        = "ER25002",
    person_id        = "ER33801",
    state            = "ER25003",
    age              = "ER25017",
    sex              = "ER25018",
    n_children       = "ER25020",
    age_yng_child    = "ER25021",
    type_du          = "ER25024",
    own_rent         = "ER25028",
    neither_own_rent = "ER25073",
    food_stamps      = "ER25683",
    wtr_adc          = "ER26050",
    amt_adc          = "ER26051",
    wtr_ssi          = "ER26066",
    amt_ssi          = "ER26068",
    wtr_welfare      = "ER26083",
    amt_welfare      = "ER26084",
    wtr_va           = "ER26100",
    amt_va           = "ER26101",
    wtr_nonva_ret    = "ER26116",
    amt_nonva_ret    = "ER26117",
    wtr_annuities    = "ER26132",
    amt_annuities    = "ER26133",
    wtr_otr_pen      = "ER26148",
    amt_otr_pen      = "ER26149",
    wtr_unemp        = "ER26165",
    amt_unemp        = "ER26166",
    wtr_workers_comp = "ER26181",
    amt_workers_comp = "ER26182",
    wtr_child_supp   = "ER26197",
    amt_child_supp   = "ER26198",
    health_head      = "ER26990",
    health_wife      = "ER27113",
    parents_poor     = "ER27390",
    race             = "ER27393",
    couple_status    = "ER28051",
    needs_standard   = "ER28039", # note: Census Needs Standard-2004 
    rural_urban      = "ER28043",
    total_income     = "ER28037", # note: Total Family Income-2004 
    education        = "ER28047",
    relation         = "ER33803",
    emp_status       = "ER33813"
  ),

  "2007" = list(
    family_id        = "ER36002",
    person_id        = "ER33901",
    state            = "ER36003",
    age              = "ER36017",
    sex              = "ER36018",
    n_children       = "ER36020",
    age_yng_child    = "ER36021",
    type_du          = "ER36024",
    own_rent         = "ER36028",
    neither_own_rent = "ER36075",
    food_stamps      = "ER36701",
    wtr_adc          = "ER37068",
    amt_adc          = "ER37069",
    wtr_ssi          = "ER37084",
    amt_ssi          = "ER37086",
    wtr_welfare      = "ER37101",
    amt_welfare      = "ER37102",
    wtr_va           = "ER37118",
    amt_va           = "ER37119",
    wtr_nonva_ret    = "ER37134",
    amt_nonva_ret    = "ER37135",
    wtr_annuities    = "ER37150",
    amt_annuities    = "ER37151",
    wtr_otr_pen      = "ER37166",
    amt_otr_pen      = "ER37167",
    wtr_unemp        = "ER37183",
    amt_unemp        = "ER37184",
    wtr_workers_comp = "ER37199",
    amt_workers_comp = "ER37200",
    wtr_child_supp   = "ER37215",
    amt_child_supp   = "ER37216",
    health_head      = "ER38202",
    health_wife      = "ER39299",
    parents_poor     = "ER37728",
    race             = "ER40565",
    couple_status    = "ER41041",
    needs_standard   = "ER41029", # note: Census Needs Standard-2006
    rural_urban      = "ER41033",
    total_income     = "ER41027", # note: Total Family Income-2006
    education        = "ER41037",
    relation         = "ER33903",
    emp_status       = "ER33913"
  ),
)
```

```{r}
# map from wide to long
df_long <- names(wave_map) %>%
  map_dfr(function(year) {
    
    # 1. Get the mapping for this specific year
    year_mapping <- wave_map[[year]]
    
    # 2. Convert to a standard named character vector: c(clean_name = "ER_code")
    rename_vec <- unlist(year_mapping)
    
    # 3. Filter to ensure every ER code in our map actually exists in the data
    rename_vec <- rename_vec[rename_vec %in% names(df_no_dupes)]
    
    # 4. Invert the vector so it matches select's expected framework:
    # select(clean_name = ER_code)
    # To do this, we want the clean names to be the vector's NAMES, and ER codes to be the VALUES
    select_vec <- setNames(rename_vec, names(rename_vec))
    
    # 5. Extract, reshape, and label
    df_no_dupes %>%
      # select() accepts a named vector where names = NEW name, values = OLD name
      select(all_of(select_vec)) %>%
      mutate(year = as.integer(year))
  })

# Move tracking keys and year to the front
df_long <- df_long %>%
  select(person_id, family_id, year, everything())
```